SELECT G.NAME, COUNT(G.NAME)
FROM   GCD_BRAND_GROUP G, GCD_INDICIA_PUBLISHER IP, GCD_PUBLISHER P
WHERE  G.PUBLISHER_ID = P.ID AND IP.PUBLISHER_ID = P.ID
       AND IP.COUNTRY_ID = (SELECT C.ID
                            FROM  STDDATA_COUNTRY C
                            WHERE C.NAME LIKE '%Belgium%')
GROUP BY G.NAME, G.ID
ORDER BY COUNT(G.NAME) DESC;
