CREATE VIEW OLDEST_PUBLISHERS AS
SELECT DISTINCT P.ID, P.NAME
FROM GCD_PUBLISHER P
ORDER BY P.YEAR_BEGAN
FETCH FIRST 10 ROWS ONLY;

SELECT OLD_P.NAME, COUNT(S.LANGUAGE_ID) AS SERIE_LANG_COUNT
FROM  OLDEST_PUBLISHERS OLD_P, GCD_SERIES S
WHERE S.PUBLISHER_ID = OLD_P.ID
GROUP BY OLD_P.NAME;
