SELECT COUNT(*) AS NUMBER_OF_PUBLISHERS
FROM GCD_PUBLISHER P
WHERE NOT EXISTS (SELECT P.ID FROM GCD_SERIES S1 WHERE S1.COUNTRY_ID=P.COUNTRY_ID AND S1.PUBLISHER_ID=P.ID)
AND EXISTS (SELECT P.ID FROM GCD_SERIES S2 WHERE S2.COUNTRY_ID!=P.COUNTRY_ID AND S2.PUBLISHER_ID=P.ID)
