SELECT G.NAME, COUNT(G.NAME)
FROM   GCD_BRAND_GROUP G, GCD_INDICIA_PUBLISHER IP, GCD_PUBLISHER P
WHERE  G.PUBLISHER_ID = P.ID AND IP.PUBLISHER_ID = P.ID
GROUP BY G.NAME
HAVING   COUNT(G.NAME) > 100
ORDER BY COUNT(G.NAME);
