CREATE VIEW QUERY_8 AS
SELECT DISTINCT P.NAME
FROM    GCD_PUBLISHER P, GCD_SERIES s
WHERE    P.ID = S.PUBLISHER_ID
AND      P.COUNTRY_ID != S.COUNTRY_ID
ORDER BY P.NAME;

SELECT C.NAME, COUNT(C.ID) AS Occurences
FROM GCD_PUBLISHER P, STDDATA_COUNTRY C, QUERY_8 Q
WHERE P.COUNTRY_ID = C.ID AND Q.NAME = P.NAME
GROUP BY C.NAME
ORDER BY COUNT(C.ID) DESC;
