select distinct S.FEATURE
from GCD_STORY S,
     GCD_STORY_TO_GENRE S2G1, GCD_STORY_GENRE G1,
     GCD_STORY_TO_GENRE S2G2, GCD_STORY_GENRE G2,
     GCD_STORY_TO_GENRE S2G3, GCD_STORY_GENRE G3
where S.ID = S2G1.STORY_ID and S2G1.GENRE_ID = G1.ID and G1.GENRE like '%humor%'
and S.ID = S2G2.STORY_ID and S2G2.GENRE_ID = G2.ID and G2.GENRE like '%crime%'
and S.ID = S2G3.STORY_ID and S2G3.GENRE_ID = G3.ID and G3.GENRE like '%romance%'
