CREATE VIEW BELGIAN_IPS_PER_PUBLISHER AS
SELECT P.ID, COUNT(IP.ID) AS BG_IPS
FROM GCD_PUBLISHER P,
     GCD_INDICIA_PUBLISHER IP
WHERE P.ID = IP.PUBLISHER_ID AND IP.COUNTRY_ID = 20
GROUP BY P.ID;

SELECT BG.NAME, BGIP.BG_IPS FROM GCD_BRAND_GROUP BG, BELGIAN_IPS_PER_PUBLISHER BGIP
WHERE BG.PUBLISHER_ID = BGIP.ID AND BGIP.BG_IPS = (SELECT MAX(BGIP2.BG_IPS) FROM BELGIAN_IPS_PER_PUBLISHER BGIP2);
