SELECT *
FROM GCD_PUBLISHER P
WHERE P.YEAR_BEGAN BETWEEN 1600 AND 2020
AND   P.YEAR_ENDED BETWEEN 1600 AND 2020;

CREATE VIEW COUNTRY_AND_DIFFERENCE AS
SELECT P.ID, C.NAME, (P.YEAR_ENDED - P.YEAR_BEGAN) AS PUBLISHING_TIME
FROM PUBLISHER_IN_YEAR_RANGE P, STDDATA_COUNTRY C
WHERE C.ID = P.COUNTRY_ID;

SELECT CAD.NAME, MAX(PUBLISHING_TIME), 
                 ROUND(AVG(PUBLISHING_TIME), 1)
FROM COUNTRY_AND_DIFFERENCE CAD
GROUP BY CAD.NAME
ORDER BY MAX(PUBLISHING_TIME) DESC
FETCH FIRST 10 ROWS ONLY;
