SELECT DISTINCT S.PUBLISHER_ID, P.NAME AS PUBLISHER_NAME
FROM   GCD_SERIES S, GCD_PUBLISHER P
WHERE  S.PUBLICATION_TYPE_ID =
          (SELECT P.ID 
           FROM   GCD_SERIES_PUBLICATION_TYPE P 
           WHERE  P.NAME = 'album')
       AND
       S.LANGUAGE_ID =
          (SELECT L.ID 
           FROM   STDDATA_LANGUAGE L 
           WHERE  L.NAME = 'Italian')
       AND
       S.PUBLISHER_ID = P.ID
       
ORDER BY S.PUBLISHER_ID DESC;
