CREATE VIEW DATE_CONVERSION AS
SELECT TO_DATE(I.PUBLICATION_DATE DEFAULT NULL ON CONVERSION ERROR, 'DD/MM/YYYY') AS CONVERTED
FROM   GCD_ISSUE I;

SELECT DISTINCT EXTRACT(YEAR FROM D.CONVERTED)
FROM   DATE_CONVERSION D
WHERE  D.CONVERTED IS NOT NULL
ORDER BY EXTRACT(YEAR FROM D.CONVERTED);
