-- Get the ID of Switzerland
CREATE VIEW SWISS_ID AS
SELECT C.ID
FROM   STDDATA_COUNTRY C
WHERE  C.NAME = 'Switzerland';

SELECT DISTINCT L.NAME
FROM GCD_PUBLISHER P,
     GCD_SERIES    S,
     STDDATA_COUNTRY  C,
     STDDATA_LANGUAGE L,
     SWISS_ID
WHERE P.COUNTRY_ID = SWISS_ID.ID
      AND S.PUBLISHER_ID = P.ID
      AND S.COUNTRY_ID  != SWISS_ID.ID
      AND S.LANGUAGE_ID = L.ID;
