CREATE VIEW SINGLE_ISSUE_ID AS
SELECT I1.ID, I1.INDICIA_PUBLISHER_ID FROM GCD_ISSUE I1
WHERE NOT EXISTS (SELECT I2.ID FROM GCD_ISSUE I2 WHERE I1.ID != I2.ID AND I1.SERIES_ID=I2.SERIES_ID AND I1.INDICIA_PUBLISHER_ID= I2.INDICIA_PUBLISHER_ID);

SELECT IP.NAME AS INDICIA_PUBLISHER_NAME, COUNT(SIID.ID) AS SINGLE_ISSUE_SERIES_COUNT FROM GCD_INDICIA_PUBLISHER IP, SINGLE_ISSUE_ID SIID
WHERE SIID.INDICIA_PUBLISHER_ID = IP.ID
GROUP BY IP.NAME
HAVING COUNT(SIID.ID)>400
ORDER BY COUNT(SIID.ID) DESC;
