SELECT DISTINCT C1.NAME
FROM STDDATA_COUNTRY C1, STDDATA_COUNTRY C2, GCD_SERIES S1, GCD_SERIES S2
WHERE C1.ID = S1.COUNTRY_ID
AND C1.NAME != 'Switzerland'
AND C2.ID = S2.COUNTRY_ID
AND C2.NAME = 'Switzerland'
AND S1.PUBLISHER_ID = S2.PUBLISHER_ID
