CREATE VIEW PUBLISHER_ID AS
SELECT DISTINCT P.ID
FROM GCD_PUBLISHER P
WHERE P.YEAR_BEGAN <= 1995 AND P.YEAR_ENDED >= 2000
   OR P.YEAR_BEGAN BETWEEN 1995 AND 2000;

SELECT P.NAME
FROM PUBLISHER_ID PUB,
     GCD_PUBLISHER P
WHERE P.ID = PUB.ID
  AND P.COUNTRY_ID =
      (SELECT C.ID
       FROM STDDATA_COUNTRY C
       WHERE C.NAME = 'Netherlands')
ORDER BY P.NAME DESC;
