CREATE VIEW DATE_CONVERSION_10 AS
SELECT TO_DATE(I.PUBLICATION_DATE DEFAULT NULL ON CONVERSION ERROR, 'MONTH YYYY') AS CONVERTED, I.ID
FROM   GCD_ISSUE I;

CREATE VIEW YEARS AS
SELECT DISTINCT EXTRACT(YEAR FROM D.CONVERTED) AS YEAR, D.ID
FROM   DATE_CONVERSION_10 D
WHERE  D.CONVERTED IS NOT NULL
ORDER BY EXTRACT(YEAR FROM D.CONVERTED);

SELECT COUNT(Y.ID), Y.YEAR
FROM YEARS Y
WHERE Y.YEAR BETWEEN 1965 AND 1975
GROUP BY Y.YEAR
ORDER BY Y.YEAR;
