SELECT * FROM
    (SELECT DISTINCT COUNT(FORMAT_1) FROM
        (SELECT EXTRACT(YEAR FROM
                TO_DATE(I.PUBLICATION_DATE DEFAULT NULL ON CONVERSION ERROR,'dd/mm/yyyy'))
                AS FORMAT_1 FROM GCD_ISSUE I)),
    (SELECT DISTINCT COUNT(FORMAT_2) FROM
        (SELECT EXTRACT(YEAR FROM
                TO_DATE(I.PUBLICATION_DATE DEFAULT NULL ON CONVERSION ERROR,'mm/dd/yyyy'))
                AS FORMAT_2 FROM GCD_ISSUE I)),
    (SELECT DISTINCT COUNT(FORMAT_3) FROM
        (SELECT EXTRACT(YEAR FROM
                TO_DATE(I.PUBLICATION_DATE DEFAULT NULL ON CONVERSION ERROR,'month yyyy'))
                AS FORMAT_3 FROM GCD_ISSUE I));
